# Generated by Django 3.1.1 on 2020-09-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20181112_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceclass',
            name='assign',
        ),
        migrations.AlterUniqueTogether(
            name='attendancetotal',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendancetotal',
            name='course',
        ),
        migrations.RemoveField(
            model_name='attendancetotal',
            name='student',
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=15),
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('8:40 - 9:30', '8:40 - 9:30'), ('9:30 - 10:20', '9:30 - 10:20'), ('10:20 - 11:10', '10:20 - 11:10'), ('11:10 - 12:00', '11:10 - 12:00'), ('12:00 - 12:50', '12:00 - 12:50'), ('12:50 - 1:40', '12:50 - 1:40'), ('1:40 - 2:30', '1:40 - 2:30'), ('2:30 - 3:30', '2:30 - 3:30'), ('3:40 - 4:20', '3:40 - 4:20')], default='3:00-3:50', max_length=50),
        ),
        migrations.AlterField(
            model_name='marks',
            name='name',
            field=models.CharField(choices=[('Internal  1', 'Internal 1'), ('Internal 2', 'Internal 2')], default='Mid 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='marksclass',
            name='name',
            field=models.CharField(choices=[('Internal  1', 'Internal 1'), ('Internal 2', 'Internal 2')], default='Mid 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AttendanceClass',
        ),
        migrations.DeleteModel(
            name='AttendanceTotal',
        ),
    ]
