# Generated by Django 3.1.1 on 2020-09-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_auto_20200907_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='name',
            field=models.CharField(choices=[('Mid 1', 'Mid 1'), ('Quiz 1', 'Quiz 1'), ('Assigment 1', 'Assigment 2'), ('Mid 2', 'Mid 2'), ('Quiz 2', 'Quiz 2'), ('Assigment 2', 'Assigment 2')], default='Mid 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='marksclass',
            name='name',
            field=models.CharField(choices=[('Mid 1', 'Mid 1'), ('Quiz 1', 'Quiz 1'), ('Assigment 1', 'Assigment 2'), ('Mid 2', 'Mid 2'), ('Quiz 2', 'Quiz 2'), ('Assigment 2', 'Assigment 2')], default='Mid 1', max_length=50),
        ),
    ]
