# Generated by Django 3.1.1 on 2020-09-10 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_auto_20200909_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='marks1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='marks',
            name='name',
            field=models.CharField(choices=[('Mid 1', 'Mid 1'), ('Quiz 1', 'Quiz 1'), ('Assigment 1', 'Assigment 1'), ('Mid 2', 'Mid 2'), ('Quiz 2', 'Quiz 2'), ('Assigment 2', 'Assigment 2')], default='Mid 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='marksclass',
            name='name',
            field=models.CharField(choices=[('Mid 1', 'Mid 1'), ('Quiz 1', 'Quiz 1'), ('Assigment 1', 'Assigment 1'), ('Mid 2', 'Mid 2'), ('Quiz 2', 'Quiz 2'), ('Assigment 2', 'Assigment 2')], default='Mid 1', max_length=50),
        ),
    ]
