# Generated by Django 3.1.1 on 2020-09-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20200910_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='name',
            field=models.CharField(choices=[('Internal test 1', 'Internal test 1'), ('Internal test 2', 'Internal test 2'), ('Assignment 1', 'Assignment 1'), ('Assignment 2', 'Assignment 2')], default='Internal test 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='marksclass',
            name='name',
            field=models.CharField(choices=[('Internal test 1', 'Internal test 1'), ('Internal test 2', 'Internal test 2'), ('Assignment 1', 'Assignment 1'), ('Assignment 2', 'Assignment 2')], default='Internal test 1', max_length=50),
        ),
    ]
