# Generated by Django 3.1.1 on 2020-09-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_auto_20200919_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='name',
            field=models.CharField(choices=[('Assignment 1', 'Assignment 1'), ('Assignment 2', 'Assignment 2'), ('Internal test 1', 'Internal test 1'), ('Internal test 2', 'Internal test 2'), ('Quiz 1', 'Quiz 1'), ('Quiz 2', 'Quiz 2'), ('Total Internal 1', 'Total Internal 1'), ('Total Internal 2', 'Total Internal 2')], default='Internal test 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='marksclass',
            name='name',
            field=models.CharField(choices=[('Assignment 1', 'Assignment 1'), ('Assignment 2', 'Assignment 2'), ('Internal test 1', 'Internal test 1'), ('Internal test 2', 'Internal test 2'), ('Quiz 1', 'Quiz 1'), ('Quiz 2', 'Quiz 2'), ('Total Internal 1', 'Total Internal 1'), ('Total Internal 2', 'Total Internal 2')], default='Internal test 1', max_length=50),
        ),
    ]
