# Generated by Django 3.1.1 on 2020-09-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_auto_20200923_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('dob', models.DateField(null=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
