# Generated by Django 3.1.1 on 2020-09-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_emailuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailUser',
        ),
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.ImageField(default=100, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='FeMale', max_length=50),
        ),
    ]
