# Generated by Django 3.1.1 on 2020-09-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_auto_20200930_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sex',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='sex',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pic',
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='login.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.DateField(default='2001-01-01'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='DOB',
            field=models.DateField(default='1999-01-01'),
        ),
    ]
