# Generated by Django 3.1.1 on 2020-09-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_auto_20200930_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='USN',
            new_name='Rollno',
        ),
    ]
