# Generated by Django 3.1.1 on 2020-10-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_auto_20200930_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Rollno',
            new_name='USN',
        ),
    ]
