# Generated by Django 3.1.1 on 2020-10-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_auto_20201001_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='USN',
            new_name='Rollno',
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('8:40 - 9:30', '8:40 - 9:30'), ('9:30 - 10:20', '9:30 - 10:20'), ('10:20 - 11:10', '10:20 - 11:10'), ('12:00 - 12:50', '12:00 - 12:50'), ('1:40 - 2:30', '1:40 - 2:30'), ('2:30 - 3:30', '2:30 - 3:30'), ('3:40 - 4:20', '3:40 - 4:20')], default='3:00-3:50', max_length=50),
        ),
    ]
